# Generated by Django 5.0.1 on 2024-02-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='name of Item')),
                ('item_price', models.CharField(max_length=300, verbose_name='Price of Item')),
                ('item_colour', models.CharField(max_length=300, verbose_name='colour of item')),
                ('item_length', models.CharField(max_length=100, verbose_name='Length of item')),
                ('image1', models.ImageField(upload_to='static/images/', verbose_name='first image of item')),
                ('image2', models.ImageField(upload_to='static/images/', verbose_name='second Image of Item')),
                ('image3', models.ImageField(upload_to='static/images/', verbose_name='third Image of Item')),
            ],
        ),
    ]
