# Generated by Django 5.0.1 on 2024-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/images/', verbose_name='first image of item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(null=True, upload_to='static/images/', verbose_name='second Image of Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(null=True, upload_to='static/images/', verbose_name='third Image of Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_colour',
            field=models.CharField(max_length=300, null=True, verbose_name='colour of item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_length',
            field=models.CharField(max_length=100, null=True, verbose_name='Length of item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, null=True, verbose_name='name of Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.CharField(max_length=300, null=True, verbose_name='Price of Item'),
        ),
    ]
