# Generated by Django 5.0.1 on 2024-02-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_item_image1_alter_item_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, null=True, verbose_name='name of Item')),
                ('item_dollar', models.CharField(max_length=300, null=True, verbose_name='Price of Item in dollars ')),
                ('item_naira', models.CharField(max_length=300, null=True, verbose_name='Price of Item in naira ')),
                ('item_colour', models.CharField(max_length=300, null=True, verbose_name='colour of item')),
                ('item_length', models.CharField(max_length=100, null=True, verbose_name='Length of item')),
                ('image1', models.ImageField(null=True, upload_to='static/images/', verbose_name='image of item')),
            ],
        ),
    ]
