# Generated by Django 5.0.1 on 2024-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_wig'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(max_length=100, null=True, verbose_name='Price Main USD'),
        ),
        migrations.AddField(
            model_name='wig',
            name='price',
            field=models.IntegerField(max_length=100, null=True, verbose_name='Price Main USD'),
        ),
    ]
