# Generated by Django 5.0.1 on 2024-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_item_price_wig_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/imagesstatic/images/', verbose_name='first image of item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(null=True, upload_to='static/imagesstatic/images/', verbose_name='second Image of Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(null=True, upload_to='static/imagesstatic/images/', verbose_name='third Image of Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.CharField(max_length=300, null=True, verbose_name='# '),
        ),
        migrations.AlterField(
            model_name='wig',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/imagesstatic/images/', verbose_name='image of item'),
        ),
        migrations.AlterField(
            model_name='wig',
            name='item_dollar',
            field=models.CharField(max_length=300, null=True, verbose_name='#'),
        ),
        migrations.AlterField(
            model_name='wig',
            name='item_naira',
            field=models.CharField(max_length=300, null=True, verbose_name='# '),
        ),
    ]
