# Generated by Django 4.0.6 on 2024-02-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_item_image1_alter_item_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, null=True, verbose_name='name of Item')),
                ('price', models.IntegerField(max_length=100, null=True, verbose_name='Price Main USD')),
                ('item_colour', models.CharField(max_length=300, null=True, verbose_name='colour of item')),
                ('item_length', models.CharField(max_length=100, null=True, verbose_name='Length of item')),
                ('image1', models.ImageField(null=True, upload_to='static/imagesstatic/images/', verbose_name='image of item')),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
        migrations.DeleteModel(
            name='wig',
        ),
    ]
