# Generated by Django 4.0.6 on 2024-02-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_wigs_delete_item_delete_wig'),
    ]

    operations = [
        migrations.AddField(
            model_name='wigs',
            name='number',
            field=models.IntegerField(default=1, max_length=100, verbose_name='number of items'),
        ),
    ]
