# Generated by Django 4.0.6 on 2024-02-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_wigs_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wigs',
            name='image1',
            field=models.ImageField(null=True, upload_to='hairbypeace/static/imagesstatic/imagesstatic/images/', verbose_name='image of item'),
        ),
    ]
