# Generated by Django 4.0.6 on 2024-02-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_wigs_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wigs',
            name='item_length',
            field=models.CharField(max_length=500, null=True, verbose_name='Length of item'),
        ),
        migrations.AlterField(
            model_name='wigs',
            name='item_name',
            field=models.CharField(max_length=500, null=True, verbose_name='name of Item'),
        ),
        migrations.AlterField(
            model_name='wigs',
            name='number',
            field=models.IntegerField(default=1, verbose_name='number of items'),
        ),
        migrations.AlterField(
            model_name='wigs',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Price Main USD'),
        ),
    ]
