# Generated by Django 4.0.6 on 2024-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_wigs_item_length_alter_wigs_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wigs',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='image of item'),
        ),
    ]
