# Generated by Django 4.0.6 on 2024-03-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.IntegerField(null=True, verbose_name='id')),
                ('username', models.CharField(max_length=500, verbose_name='username')),
            ],
        ),
    ]
