# Generated by Django 4.0.6 on 2024-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_cart_wigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_wigs',
            name='username',
            field=models.CharField(max_length=500, null=True, verbose_name='username'),
        ),
    ]
