# Generated by Django 4.0.6 on 2024-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_cart_wigs_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500, null=True, verbose_name='name of Item')),
                ('number', models.IntegerField(default=1, verbose_name='number of items')),
                ('item_colour', models.CharField(max_length=300, null=True, verbose_name='colour of item')),
                ('item_length', models.CharField(max_length=500, null=True, verbose_name='Length of item')),
                ('image1', models.ImageField(null=True, upload_to='images/', verbose_name='image of item')),
                ('image2', models.ImageField(null=True, upload_to='images/', verbose_name='image of item')),
                ('image3', models.ImageField(null=True, upload_to='images/', verbose_name='image of item')),
            ],
        ),
    ]
