# Generated by Django 4.0.6 on 2024-03-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_bundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='bundleoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_field', models.CharField(choices=[('single', 'single'), ('double', 'double'), ('superdouble', 'superdouble')], max_length=20, verbose_name='Drawn')),
                ('choice_field2', models.CharField(choices=[('natural', 'natural'), ('bone', 'bone'), ('kinky', 'kinky'), ('body', 'body'), ('eurasian', 'eurasian'), ('pano', 'pano'), ('deep', 'deep'), ('magic', 'magic'), ('wavy', 'wavy')], max_length=20, verbose_name='Style')),
                ('choice_field3', models.CharField(choices=[('8', '8'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('24', '24'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32')], max_length=20, verbose_name='Length')),
                ('choice_field4', models.CharField(choices=[('natural', 'natural'), ('blonde', 'blonde'), ('green', 'green'), ('pink', 'pink'), ('baby-pink', 'baby-pink'), ('red', 'red'), ('orange', 'orange'), ('ginger', 'ginger'), ('brown', 'brown'), ('purple', 'purple'), ('black', 'black')], max_length=20, verbose_name='Color')),
                ('price', models.IntegerField(null=True, verbose_name='Price Main USD')),
            ],
        ),
    ]
