# Generated by Django 4.0.6 on 2024-03-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_bundleoptions_choice_field3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleoptions',
            name='choice_field3',
            field=models.CharField(choices=[('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('22', '22'), ('24', '24'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32')], max_length=20, verbose_name='Length'),
        ),
    ]
