# Generated by Django 4.0.6 on 2024-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_bundleoptions_choice_field3'),
    ]

    operations = [
        migrations.CreateModel(
            name='double_drawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(max_length=500, null=True, verbose_name='length')),
                ('price', models.IntegerField(null=True, verbose_name='Price Main USD')),
            ],
        ),
        migrations.CreateModel(
            name='single_drawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(max_length=500, null=True, verbose_name='length')),
                ('price', models.IntegerField(null=True, verbose_name='Price Main USD')),
            ],
        ),
        migrations.CreateModel(
            name='superdouble_drawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(max_length=500, null=True, verbose_name='length')),
                ('price', models.IntegerField(null=True, verbose_name='Price Main USD')),
            ],
        ),
    ]
