# Generated by Django 4.0.6 on 2024-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_double_drawn_single_drawn_superdouble_drawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='item_colour',
            field=models.CharField(default='Natural color', max_length=300, null=True, verbose_name='colour of item'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='item_length',
            field=models.CharField(default='12-40inches', max_length=500, null=True, verbose_name='Length of item'),
        ),
    ]
