# Generated by Django 4.0.6 on 2024-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_bundle_item_colour_alter_bundle_item_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='bundlecart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, null=True, verbose_name='username')),
                ('image', models.CharField(max_length=500, null=True, verbose_name='image')),
                ('product', models.CharField(max_length=500, null=True, verbose_name='Product')),
            ],
        ),
    ]
