# Generated by Django 4.0.6 on 2024-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_bundlecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlecart',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Price Main USD'),
        ),
    ]
