# Generated by Django 4.0.6 on 2024-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_bundlecart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, null=True, verbose_name='username')),
                ('email', models.EmailField(max_length=500, null=True, verbose_name='Email')),
                ('phone', models.IntegerField(max_length=500, null=True, verbose_name='Phone No')),
                ('price', models.IntegerField(null=True, verbose_name='Price Main USD')),
            ],
        ),
    ]
