# Generated by Django 4.0.6 on 2024-05-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_customer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='country',
            field=models.CharField(max_length=500, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='customer_details',
            name='state',
            field=models.CharField(max_length=500, null=True, verbose_name='state'),
        ),
    ]
